<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Users\bbdnet0518\Documents\GitHub\vodatest\bin\Debug\TestProj.dll" total="1" errors="1" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2014-12-09" time="12:58:01">
  <environment nunit-version="2.6.3.13283" clr-version="2.0.50727.8000" os-version="Microsoft Windows NT 6.2.9200.0" platform="Win32NT" cwd="C:\Program Files (x86)\NUnit 2.6.3\bin" machine-name="TONYV" user="bbdnet0518" user-domain="BBDNET" />
  <culture-info current-culture="en-ZA" current-uiculture="en-US" />
  <test-suite type="Assembly" name="C:\Users\bbdnet0518\Documents\GitHub\vodatest\bin\Debug\TestProj.dll" executed="True" result="Failure" success="False" time="69.057" asserts="0">
    <results>
      <test-suite type="Namespace" name="TestProj" executed="True" result="Failure" success="False" time="69.055" asserts="0">
        <results>
          <test-suite type="Namespace" name="Tests" executed="True" result="Failure" success="False" time="69.054" asserts="0">
            <results>
              <test-suite type="Namespace" name="Orders" executed="True" result="Failure" success="False" time="69.053" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="Orders" description="Orders" executed="True" result="Failure" success="False" time="69.051" asserts="0">
                    <categories>
                      <category name="Orders" />
                    </categories>
                    <results>
                      <test-case name="TestProj.Tests.Orders.Orders._04_OrderHistoryExpanded" description="_04_OrderHistoryExpanded" executed="True" result="Error" success="False" time="8.507" asserts="0">
                        <categories>
                          <category name="Orders" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[FluentAutomation.Exceptions.FluentException : An unexpected exception was thrown inside WaitUntil(Action). See InnerException for details.
  ----> OpenQA.Selenium.StaleElementReferenceException : stale element reference: element is not attached to the page document
  (Session info: chrome=39.0.2171.71)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.3 x86_64)]]></message>
                          <stack-trace><![CDATA[at DynamicModule.ns.Wrapped_IOrdersActions_2db88436aad348d7a245730d027a5e86.VerifyConfirmedOrder(Browser browserInstance)
at TestProj.Tests.Orders.Orders._04_OrderHistoryExpanded() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\Orders\Orders.cs:line 236
--StaleElementReferenceException
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebElement.get_TagName()
at FluentAutomation.Element..ctor(IWebElement webElement, String selector)
at FluentAutomation.CommandProvider.<>c__DisplayClass8.<Find>b__7()
at FluentAutomation.ElementProxy.get_Element()
at FluentAutomation.CommandProvider.<>c__DisplayClass18.<Click>b__17()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>