<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Users\bbdnet0518\Documents\GitHub\vodatest\bin\Debug\TestProj.dll" total="1" errors="0" failures="1" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2014-12-02" time="10:01:38">
  <environment nunit-version="2.6.3.13283" clr-version="2.0.50727.8000" os-version="Microsoft Windows NT 6.2.9200.0" platform="Win32NT" cwd="C:\Program Files (x86)\NUnit 2.6.3\bin" machine-name="TONYV" user="bbdnet0518" user-domain="BBDNET" />
  <culture-info current-culture="en-ZA" current-uiculture="en-US" />
  <test-suite type="Assembly" name="C:\Users\bbdnet0518\Documents\GitHub\vodatest\bin\Debug\TestProj.dll" executed="True" result="Failure" success="False" time="22.609" asserts="0">
    <results>
      <test-suite type="Namespace" name="TestProj" executed="True" result="Failure" success="False" time="22.592" asserts="0">
        <results>
          <test-suite type="Namespace" name="Tests" executed="True" result="Failure" success="False" time="22.592" asserts="0">
            <results>
              <test-suite type="Namespace" name="AccessingApplication" executed="True" result="Failure" success="False" time="22.592" asserts="0">
                <results>
                  <test-suite type="TestFixture" name="AccessingApplication" description="AccessingApplication" executed="True" result="Error" success="False" time="22.586" asserts="0">
                    <categories>
                      <category name="AccessingApplication" />
                    </categories>
                    <failure>
                      <message><![CDATA[SetUp : FluentAutomation.Exceptions.FluentException : Conditional wait passed the timeout [5000ms] for expression [ => Invoke(value(FluentAutomation.BaseCommandProvider+<>c__DisplayClass0).action)]. See InnerException for details of the last FluentException thrown.
  ----> FluentAutomation.Exceptions.FluentAssertFailedException : Expected element matching selector [#messageBlock > ul > li:nth-child(1) > div > div:nth-child(3) > ul > li] to exist.]]></message>
                      <stack-trace><![CDATA[at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
at FluentAutomation.BaseCommandProvider.Act(CommandType commandType, Action action)
at FluentAutomation.BaseCommandProvider.WaitUntil(Expression`1 conditionAction, TimeSpan timeout)
at FluentAutomation.BaseCommandProvider.Act(CommandType commandType, Action action)
at FluentAutomation.CommandProvider.FluentAutomation.Interfaces.ICommandProvider.Act(CommandType , Action )
at FluentAutomation.AssertProvider.Exists(String selector)
at FluentAutomation.AssertSyntaxProvider.Exists(String selector)
at TestProj.Tests.AccessingApplication.AccessingApplication.activate(Browser browserInstance) in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\AccessingApplication\AccessingApplication.cs:line 119
at TestProj.Tests.AccessingApplication.AccessingApplication.Initialise() in c:\Users\bbdnet0518\Documents\GitHub\vodatest\Tests\AccessingApplication\AccessingApplication.cs:line 49
--FluentAssertFailedException
at FluentAutomation.AssertProvider.ReportError(String message, Object[] formatParams)
at FluentAutomation.AssertProvider.<>c__DisplayClass6b.<Exists>b__6a()
at FluentAutomation.BaseCommandProvider.<>c__DisplayClass9.<WaitUntil>b__8()
]]></stack-trace>
                    </failure>
                    <results>
                      <test-case name="TestProj.Tests.AccessingApplication.AccessingApplication._01_ActivationLandingPage" description="_01_ActivationLandingPage" executed="True" result="Failure" success="False" time="0.000" asserts="0">
                        <categories>
                          <category name="Accessing app" />
                        </categories>
                        <properties>
                          <property name="Repeat" value="1" />
                        </properties>
                        <failure>
                          <message><![CDATA[TestFixtureSetUp failed in AccessingApplication]]></message>
                          <stack-trace />
                        </failure>
                      </test-case>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>